# version: '3.8'
services:
  test-db:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgresql123
      POSTGRES_PASSWORD: briltest
      POSTGRES_DB: nest
    networks:
      - briltest

  dev-db:
    image: postgres:13
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    networks:
      - briltest

networks:
  briltest:
